### ISSUE TITLE
can't use calc with this plugin

### ISSUE THREAD

**Issue by claudewowo** [gladkih/postcss-units#7]
![image](https://user-images.githubusercontent.com/8219715/36588788-283a7426-18c4-11e8-8045-ed9d07511b6c.png)

css:
font-size: calc(700% - rem(90));

error:
Module build failed: Error: Parse error on line 1:
    700% - rem(90)
    -------^
    Expecting 'SUB', 'LPAREN', 'NESTED_CALC', 'NUMBER', 'CSS_VAR', 'LENGTH', 'ANGLE', 'TIME', 'FREQ', 'RES', 'EMS', 'EXS', 'CHS', 'REMS', 'VHS', 'VWS', 'VMINS', 'VMAXS', 'PERCENTAGE', got 'PREFIX'

**Comment by gladkih** [comment]
I'll see what I can do.

**Comment by claudewowo** [comment]
There is another case, using the postcss-cssnext plugin before the postcss-units, it will be two units in css, like this:     
![image](https://user-images.githubusercontent.com/8219715/36623324-8c4d3eb0-193e-11e8-9f61-a572b079d847.png)
If using the postcss-units plugin before the postcss-cssnext, u will get error information below:
 
Module build failed: Error: Parse error on line 1:
700% - rem(90)
-------^
Expecting 'SUB', 'LPAREN', 'NESTED_CALC', 'NUMBER', 'CSS_VAR', 'LENGTH', 'ANGLE', 'TIME', 'FREQ', 'RES', 'EMS', 'EXS', 'CHS', 'REMS', 'VHS', 'VWS', 'VMINS', 'VMAXS', 'PERCENTAGE', got 'PREFIX'

It's my config in the postcss.config.js:

module.exports = {
    plugins: [
        require('postcss-import')({
            path: ['resources/assets/']
        }),
        require('postcss-assets')({
            loadPaths: ['resources/assets/common/']
        }),
        require('postcss-nested'),
        require('postcss-color-function'),
        require('postcss-mixins'),
        require('postcss-extend'),
        require('postcss-units')({
            size: 75,
            fallback: false,
            precision: 4
        }),
        require('postcss-cssnext'),
        require('cssnano')({
            sourcemap: true,
            safe: true,
            discardComments: {
                removeAll: false,
            },
            discardUnused: false,
            zindex: false,
        }),
    ]
}

I hope you can help me， 3Q~

**Comment by gladkih** [comment]
This case work. Look this test https://github.com/gladkih/postcss-units/blob/master/test.js#L70
